// Generated by Pigeon — FAQ page (visible Q&A + FAQPage schema).
export const metadata = { title: "FAQ" };
export default function FaqPage() {
  return (
    <main>
      <h1>Frequently asked questions</h1>
      <section>
        <h2>{"How important are soft skills when hiring freelancers?"}</h2>
        <p>{"Soft skills are crucial when hiring freelancers, as they enhance communication and collaboration. At Bridge Creatives, we prioritize these qualities to ensure a better fit for your team."}</p>
      </section>
      <section>
        <h2>{"What are the best practices for remote freelancer hiring?"}</h2>
        <p>{"Best practices include clear communication, thorough vetting, and focusing on soft skills. Bridge Creatives helps you find freelancers who excel in these areas."}</p>
      </section>
      <section>
        <h2>{"What is the cost of hiring vetted creative freelancers?"}</h2>
        <p>{"The cost varies based on the freelancer's experience and project scope. Bridge Creatives offers competitive rates for high-quality vetted freelancers."}</p>
      </section>
      <section>
        <h2>{"How can I hire freelancers who communicate well?"}</h2>
        <p>{"To hire freelancers who communicate effectively, prioritize soft skills during the selection process. Bridge Creatives specializes in matching you with such freelancers."}</p>
      </section>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: "{\n  \"@context\": \"https://schema.org\",\n  \"@type\": \"FAQPage\",\n  \"mainEntity\": [\n    {\n      \"@type\": \"Question\",\n      \"name\": \"How important are soft skills when hiring freelancers?\",\n      \"acceptedAnswer\": {\n        \"@type\": \"Answer\",\n        \"text\": \"Soft skills are crucial when hiring freelancers, as they enhance communication and collaboration. At Bridge Creatives, we prioritize these qualities to ensure a better fit for your team.\"\n      }\n    },\n    {\n      \"@type\": \"Question\",\n      \"name\": \"What are the best practices for remote freelancer hiring?\",\n      \"acceptedAnswer\": {\n        \"@type\": \"Answer\",\n        \"text\": \"Best practices include clear communication, thorough vetting, and focusing on soft skills. Bridge Creatives helps you find freelancers who excel in these areas.\"\n      }\n    },\n    {\n      \"@type\": \"Question\",\n      \"name\": \"What is the cost of hiring vetted creative freelancers?\",\n      \"acceptedAnswer\": {\n        \"@type\": \"Answer\",\n        \"text\": \"The cost varies based on the freelancer's experience and project scope. Bridge Creatives offers competitive rates for high-quality vetted freelancers.\"\n      }\n    },\n    {\n      \"@type\": \"Question\",\n      \"name\": \"How can I hire freelancers who communicate well?\",\n      \"acceptedAnswer\": {\n        \"@type\": \"Answer\",\n        \"text\": \"To hire freelancers who communicate effectively, prioritize soft skills during the selection process. Bridge Creatives specializes in matching you with such freelancers.\"\n      }\n    }\n  ]\n}" }} />
    </main>
  );
}
