// Generated by Pigeon — Organization identity for AI search. Reviewed via PR.
export default function PigeonSchema() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: "{\n  \"@context\": \"https://schema.org\",\n  \"@type\": \"Organization\",\n  \"@id\": \"https://bridgecreatives.co/#organization\",\n  \"name\": \"Bridge Creatives\",\n  \"url\": \"https://bridgecreatives.co\",\n  \"sameAs\": [\n    \"https://linkedin.com/company/bridgecreatives\",\n    \"https://www.crunchbase.com/organization/bridgecreatives\",\n    \"https://www.g2.com/products/bridge-creatives/reviews\"\n  ],\n  \"logo\": \"https://bridgecreatives.co/logo.png\"\n}" }} />
    </>
  );
}
